CREATE TABLE Staff
(staffId INT GENERATED ALWAYS AS IDENTITY NOT NULL,
staffName VARCHAR(32) NOT NULL,
staffEmail VARCHAR(32) NOT NULL,
staffPhone INT,
rank INT,
staffPassword VARCHAR(32) NOT NULL,
staffManager INT,
PRIMARY KEY (staffId));